version: "3.9"
services:
  flaskapp:
    build:
      context: ./app
      args:
        ENV: PROD
    volumes:
      - type: bind
        source: ${VIDEO_PATH}
        target: /app/videos
      - type: bind
        source: ${LOG_PATH}
        target: /app/logs

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ${VIDEO_PATH}
        target: /videos
    depends_on:
      - flaskapp
